kind: pipeline
type: ssh
name: 部署微服务-mycqu-微服务

server:
  host:
    from_secret: ssh_host
  user: root
  ssh_key:
    from_secret: ssh_key

platform:
  os: linux
  arсh: amd64

clone:
  disable: true

steps:
  - name: clone
    commands:
      - git config --global http.proxy http://127.0.0.1:7890
      - git config --global https.proxy http://127.0.0.1:7890
      - git clone https://github.com/321CQU/Mycqu_Service.git
      - cd ./Mycqu_Service/
      - git checkout main

  - name: 新建镜像
    commands:
      - source $${_321CQU_PUBLIC_REPOSITORY_PATH}/.env
      - cd ./Mycqu_Service/
      - docker build -t $${MYCQU_SERVICE_IMAGE} .
      - cd $${_321CQU_PUBLIC_REPOSITORY_PATH}
      - docker-compose up -d $${MYCQU_SERVICE_SERVER_NAME}
      - docker image prune -f
    environment:
      PROXY_PASSWORD:
        from_secret: proxy_password
      PROXY_USERNAME:
        from_secret: proxy_username
      PROXY_SECRET_ID:
        from_secret: proxy_secret_id
      PROXY_SIGNATURE:
        from_secret: proxy_signature
    depends_on:
      - clone

trigger:
  branch:
    - main
  event:
    - push
    - merge

---
kind: pipeline
type: docker
name: 通知

clone:
  disable: true

steps:
  - name: 钉钉通知
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      secret:
        from_secret: dingtalk_sign
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true

trigger:
  branch:
    - main
  event:
    - push
    - merge
  status:
    - success
    - failure

depends_on:
  - 部署微服务-mycqu-微服务

